#include "Tools/DeleteBlueprintNodeTool.h"
#include "Dom/JsonObject.h"
#include "Engine/Blueprint.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "ScopedTransaction.h"
#include "Tools/BlueprintEditToolUtils.h"
#include "Tools/BlueprintGraphEditToolUtils.h"
#include "Tools/BlueprintToolUtils.h"
FDeleteBlueprintNodeTool::FDeleteBlueprintNodeTool():FMCPToolBase(TEXT("DeleteBlueprintNode"),TEXT("Deletes one Blueprint graph node by stable GUID. Requires confirm=true, supports dry-run, and reports affected pin links.")){}
UnrealMCP::FMCPResponse FDeleteBlueprintNodeTool::Execute(const UnrealMCP::FMCPRequest&Request)const{FString O,G,GG,N;if(!Request.Params.IsValid()||!Request.Params->TryGetStringField(TEXT("objectPath"),O)||!Request.Params->TryGetStringField(TEXT("nodeGuid"),N))return BuildError(Request,UnrealMCP::EMCPErrorCode::InvalidParams,TEXT("DeleteBlueprintNode requires objectPath, nodeGuid, and graphName or graphGuid."));Request.Params->TryGetStringField(TEXT("graphName"),G);Request.Params->TryGetStringField(TEXT("graphGuid"),GG);if(G.IsEmpty()&&GG.IsEmpty())return BuildError(Request,UnrealMCP::EMCPErrorCode::InvalidParams,TEXT("DeleteBlueprintNode requires graphName or graphGuid."));bool Dry=UnrealMCP::BlueprintEditToolUtils::GetOptionalBool(Request.Params,TEXT("dryRun"),false),Confirm=UnrealMCP::BlueprintEditToolUtils::GetOptionalBool(Request.Params,TEXT("confirm"),false),Save=UnrealMCP::BlueprintEditToolUtils::GetOptionalBool(Request.Params,TEXT("saveAfterEdit"),false);if(!Dry&&!Confirm)return BuildError(Request,UnrealMCP::EMCPErrorCode::InvalidParams,TEXT("DeleteBlueprintNode requires confirm=true unless dryRun=true."));int32 Links=0;FString Title,File,IdxErr,ExecErr;bool Idx=false;bool Ok=UnrealMCP::BlueprintToolUtils::ExecuteOnGameThreadSync([&](FString&E){UBlueprint*B=nullptr;if(!UnrealMCP::BlueprintEditToolUtils::ResolveBlueprint(O,B,E))return false;UEdGraph*Graph=nullptr;if(!UnrealMCP::BlueprintGraphEditToolUtils::ResolveGraph(B,G,GG,Graph,E))return false;UEdGraphNode*Node=nullptr;if(!UnrealMCP::BlueprintGraphEditToolUtils::ResolveNode(Graph,N,Node,E))return false;Title=Node->GetNodeTitle(ENodeTitleType::ListView).ToString();for(UEdGraphPin*P:Node->Pins)if(P)Links+=P->LinkedTo.Num();if(Dry)return true;const FScopedTransaction T(NSLOCTEXT("UnrealMCP","DeleteBlueprintNode","UnrealMCP Delete Blueprint Node"));B->Modify();Graph->Modify();Node->Modify();FBlueprintEditorUtils::RemoveNode(B,Node,true);FBlueprintEditorUtils::MarkBlueprintAsModified(B);return UnrealMCP::BlueprintGraphEditToolUtils::SaveAndRefreshIfRequested(B,O,Save,File,Idx,IdxErr,E);},ExecErr);if(!Ok)return BuildError(Request,UnrealMCP::EMCPErrorCode::InternalError,ExecErr);UnrealMCP::FMCPResponse R;R.Id=Request.Id;auto J=BuildBooleanResult(true);J->SetStringField(TEXT("objectPath"),O);J->SetStringField(TEXT("nodeGuid"),N);J->SetStringField(TEXT("nodeTitle"),Title);J->SetNumberField(TEXT("affectedPinLinkCount"),Links);J->SetBoolField(TEXT("dryRun"),Dry);J->SetBoolField(TEXT("deleted"),!Dry);J->SetBoolField(TEXT("saved"),Save&&!Dry);J->SetBoolField(TEXT("indexRefreshed"),Idx);J->SetStringField(TEXT("indexRefreshError"),IdxErr);R.Result=J;return R;}
TSharedPtr<FJsonObject>FDeleteBlueprintNodeTool::BuildInputSchema()const{using namespace UnrealMCP::BlueprintEditToolUtils;auto S=MakeShared<FJsonObject>();S->SetStringField(TEXT("type"),TEXT("object"));auto P=MakeShared<FJsonObject>();P->SetObjectField(TEXT("objectPath"),BuildStringProperty(TEXT("Target Blueprint.")));P->SetObjectField(TEXT("graphName"),BuildStringProperty(TEXT("Stable graph name.")));P->SetObjectField(TEXT("graphGuid"),BuildStringProperty(TEXT("Exact graph GUID.")));P->SetObjectField(TEXT("nodeGuid"),BuildStringProperty(TEXT("Exact node GUID.")));P->SetObjectField(TEXT("confirm"),BuildBoolProperty(TEXT("Required for deletion.")));P->SetObjectField(TEXT("dryRun"),BuildBoolProperty(TEXT("Report impact without deletion.")));P->SetObjectField(TEXT("saveAfterEdit"),BuildBoolProperty(TEXT("Save and refresh after deletion.")));S->SetObjectField(TEXT("properties"),P);TArray<TSharedPtr<FJsonValue>>Q{MakeShared<FJsonValueString>(TEXT("objectPath")),MakeShared<FJsonValueString>(TEXT("nodeGuid"))};S->SetArrayField(TEXT("required"),Q);return S;}
