#include "Tools/MoveBlueprintNodeTool.h"
#include "Dom/JsonObject.h"
#include "Engine/Blueprint.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "ScopedTransaction.h"
#include "Tools/BlueprintEditToolUtils.h"
#include "Tools/BlueprintGraphEditToolUtils.h"
#include "Tools/BlueprintToolUtils.h"

FMoveBlueprintNodeTool::FMoveBlueprintNodeTool():FMCPToolBase(TEXT("MoveBlueprintNode"),TEXT("Moves a Blueprint node using explicit or relative collision-aware placement. Supports dry-run and optional save.")){}
UnrealMCP::FMCPResponse FMoveBlueprintNodeTool::Execute(const UnrealMCP::FMCPRequest&Request)const
{
 FString O,G,GG,N;if(!Request.Params.IsValid()||!Request.Params->TryGetStringField(TEXT("objectPath"),O)||!Request.Params->TryGetStringField(TEXT("nodeGuid"),N))return BuildError(Request,UnrealMCP::EMCPErrorCode::InvalidParams,TEXT("MoveBlueprintNode requires objectPath, nodeGuid, and graphName or graphGuid."));Request.Params->TryGetStringField(TEXT("graphName"),G);Request.Params->TryGetStringField(TEXT("graphGuid"),GG);if(G.IsEmpty()&&GG.IsEmpty())return BuildError(Request,UnrealMCP::EMCPErrorCode::InvalidParams,TEXT("MoveBlueprintNode requires graphName or graphGuid."));bool Dry=UnrealMCP::BlueprintEditToolUtils::GetOptionalBool(Request.Params,TEXT("dryRun"),false),Save=UnrealMCP::BlueprintEditToolUtils::GetOptionalBool(Request.Params,TEXT("saveAfterEdit"),false);int32 OldX=0,OldY=0;UnrealMCP::BlueprintGraphEditToolUtils::FPlacement P;FString File,IdxErr,ExecErr;bool Idx=false;
 bool Ok=UnrealMCP::BlueprintToolUtils::ExecuteOnGameThreadSync([&](FString&E){UBlueprint*B=nullptr;if(!UnrealMCP::BlueprintEditToolUtils::ResolveBlueprint(O,B,E))return false;UEdGraph*Graph=nullptr;if(!UnrealMCP::BlueprintGraphEditToolUtils::ResolveGraph(B,G,GG,Graph,E))return false;UEdGraphNode*Node=nullptr;if(!UnrealMCP::BlueprintGraphEditToolUtils::ResolveNode(Graph,N,Node,E))return false;OldX=Node->NodePosX;OldY=Node->NodePosY;P=UnrealMCP::BlueprintGraphEditToolUtils::ResolvePlacement(Graph,Request.Params,E);if(!E.IsEmpty())return false;if(Dry)return true;const FScopedTransaction T(NSLOCTEXT("UnrealMCP","MoveBlueprintNode","UnrealMCP Move Blueprint Node"));B->Modify();Graph->Modify();Node->Modify();Node->NodePosX=P.X;Node->NodePosY=P.Y;FBlueprintEditorUtils::MarkBlueprintAsModified(B);return UnrealMCP::BlueprintGraphEditToolUtils::SaveAndRefreshIfRequested(B,O,Save,File,Idx,IdxErr,E);},ExecErr);if(!Ok)return BuildError(Request,UnrealMCP::EMCPErrorCode::InternalError,ExecErr);UnrealMCP::FMCPResponse R;R.Id=Request.Id;auto J=BuildBooleanResult(true);J->SetStringField(TEXT("objectPath"),O);J->SetStringField(TEXT("nodeGuid"),N);J->SetBoolField(TEXT("dryRun"),Dry);J->SetNumberField(TEXT("oldPositionX"),OldX);J->SetNumberField(TEXT("oldPositionY"),OldY);J->SetNumberField(TEXT("positionX"),P.X);J->SetNumberField(TEXT("positionY"),P.Y);J->SetBoolField(TEXT("collisionAdjusted"),P.bCollisionAdjusted);J->SetBoolField(TEXT("saved"),Save&&!Dry);J->SetBoolField(TEXT("indexRefreshed"),Idx);J->SetStringField(TEXT("indexRefreshError"),IdxErr);R.Result=J;return R;
}
TSharedPtr<FJsonObject> FMoveBlueprintNodeTool::BuildInputSchema()const{using namespace UnrealMCP::BlueprintEditToolUtils;auto S=MakeShared<FJsonObject>();S->SetStringField(TEXT("type"),TEXT("object"));auto P=MakeShared<FJsonObject>();P->SetObjectField(TEXT("objectPath"),BuildStringProperty(TEXT("Target Blueprint.")));P->SetObjectField(TEXT("graphName"),BuildStringProperty(TEXT("Stable or unique graph name.")));P->SetObjectField(TEXT("graphGuid"),BuildStringProperty(TEXT("Exact graph GUID.")));P->SetObjectField(TEXT("nodeGuid"),BuildStringProperty(TEXT("Exact node GUID.")));P->SetObjectField(TEXT("relativeToNodeGuid"),BuildStringProperty(TEXT("Optional placement anchor.")));auto I=MakeShared<FJsonObject>();I->SetStringField(TEXT("type"),TEXT("integer"));P->SetObjectField(TEXT("positionX"),I);P->SetObjectField(TEXT("positionY"),I);P->SetObjectField(TEXT("horizontalSpacing"),I);P->SetObjectField(TEXT("verticalOffset"),I);P->SetObjectField(TEXT("dryRun"),BuildBoolProperty(TEXT("Preview placement.")));P->SetObjectField(TEXT("saveAfterEdit"),BuildBoolProperty(TEXT("Save and refresh.")));S->SetObjectField(TEXT("properties"),P);TArray<TSharedPtr<FJsonValue>>Req{MakeShared<FJsonValueString>(TEXT("objectPath")),MakeShared<FJsonValueString>(TEXT("nodeGuid"))};S->SetArrayField(TEXT("required"),Req);return S;}
