#include "Tools/RefreshBlueprintCallSitesEngine.h"

#include "Editor.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphPin.h"
#include "Engine/Blueprint.h"
#include "K2Node_CallFunction.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "MCP/MutationRequestTracker.h"
#include "ScopedTransaction.h"
#include "Tools/BlueprintEditToolUtils.h"
#include "Tools/BlueprintGraphEditToolUtils.h"
#include "Tools/BlueprintToolUtils.h"
#include "UObject/Package.h"

namespace
{
    using namespace UnrealMCP;

    struct FPinSnapshot
    {
        FString PinId;
        FString PinName;
        EEdGraphPinDirection Direction = EGPD_Input;
    };

    // The index stores graph_name as "Name::GraphGuid::AssetPath:Name" (see BlueprintGraphEditToolUtils::ResolveGraph),
    // not a plain UEdGraph::GetName(), so resolution must go through the same shared helper the rest of the
    // plugin uses for index-sourced graph identifiers rather than a raw name comparison.
    UEdGraphNode* FindCallSiteNode(UBlueprint* Blueprint, const FString& GraphName, const FString& NodeGuid, UEdGraph*& OutGraph, FString& OutError)
    {
        OutGraph = nullptr;
        if (!BlueprintGraphEditToolUtils::ResolveGraph(Blueprint, GraphName, FString(), OutGraph, OutError))
        {
            return nullptr;
        }
        UEdGraphNode* Node = nullptr;
        if (!BlueprintGraphEditToolUtils::ResolveNode(OutGraph, NodeGuid, Node, OutError))
        {
            return nullptr;
        }
        return Node;
    }

    TArray<FPinSnapshot> SnapshotPins(const UK2Node_CallFunction* Node)
    {
        TArray<FPinSnapshot> Snapshot;
        for (const UEdGraphPin* Pin : Node->Pins)
        {
            if (Pin == nullptr)
            {
                continue;
            }
            FPinSnapshot Item;
            Item.PinId = BlueprintGraphEditToolUtils::GetPinId(Pin);
            Item.PinName = Pin->PinName.ToString();
            Item.Direction = Pin->Direction;
            Snapshot.Add(MoveTemp(Item));
        }
        return Snapshot;
    }

    bool FindMatchingRow(const TArray<FPinSnapshot>& Rows, const FString& Name, EEdGraphPinDirection Direction, FPinSnapshot& OutRow)
    {
        for (const FPinSnapshot& Row : Rows)
        {
            if (Row.Direction == Direction && Row.PinName.Equals(Name, ESearchCase::IgnoreCase))
            {
                OutRow = Row;
                return true;
            }
        }
        return false;
    }

    // Proves a rolled-back node returned to its original signature. Pin IDs are regenerated by both
    // ReconstructNode() and the undo that restores it, so restoration can only be verified by
    // comparing pin shape (name + direction), never by comparing the recorded pin IDs.
    bool PinShapesMatch(const TArray<FPinSnapshot>& Left, const TArray<FPinSnapshot>& Right)
    {
        if (Left.Num() != Right.Num())
        {
            return false;
        }
        auto ShapeKeys = [](const TArray<FPinSnapshot>& Pins)
        {
            TArray<FString> Keys;
            Keys.Reserve(Pins.Num());
            for (const FPinSnapshot& Pin : Pins)
            {
                Keys.Add(FString::Printf(TEXT("%s|%s"), *Pin.PinName.ToLower(), Pin.Direction == EGPD_Input ? TEXT("in") : TEXT("out")));
            }
            Keys.Sort();
            return Keys;
        };
        return ShapeKeys(Left) == ShapeKeys(Right);
    }

    // One indexed call site's outcome. Retaining the pre-mutation pin shape is what allows the
    // rollback path to report measured restoration instead of assuming the undo worked.
    struct FNodeOutcome
    {
        FString NodeGuid;
        FString GraphName;
        bool bFound = false;
        TArray<FPinSnapshot> BeforePins;
        TSharedPtr<FJsonObject> Evidence;
        FString Error;
    };

    // Reconstructs one caller node in-place: Unreal's UK2Node::ReconstructNode() re-derives pins from
    // SetFromFunction()/GetTargetFunction() and rewires old links onto matching-named new pins itself,
    // orphaning (not silently dropping) any pin whose name no longer exists on the new signature.
    TSharedRef<FJsonObject> ReconstructNode(UK2Node_CallFunction* Node, const FString& NodeGuid, const FString& GraphName, TArray<FPinSnapshot>& OutBeforePins)
    {
        const TArray<FPinSnapshot> OldPins = SnapshotPins(Node);
        OutBeforePins = OldPins;
        Node->Modify();
        Node->ReconstructNode();
        const TArray<FPinSnapshot> NewPins = SnapshotPins(Node);

        TArray<TSharedPtr<FJsonValue>> Mapping;
        TArray<TSharedPtr<FJsonValue>> Orphaned;
        for (const FPinSnapshot& OldPin : OldPins)
        {
            FPinSnapshot NewMatch;
            if (FindMatchingRow(NewPins, OldPin.PinName, OldPin.Direction, NewMatch))
            {
                TSharedRef<FJsonObject> Item = MakeShared<FJsonObject>();
                Item->SetStringField(TEXT("pinName"), OldPin.PinName);
                Item->SetStringField(TEXT("direction"), OldPin.Direction == EGPD_Input ? TEXT("input") : TEXT("output"));
                Item->SetStringField(TEXT("oldPinId"), OldPin.PinId);
                Item->SetStringField(TEXT("newPinId"), NewMatch.PinId);
                Mapping.Add(MakeShared<FJsonValueObject>(Item));
            }
            else
            {
                Orphaned.Add(MakeShared<FJsonValueString>(OldPin.PinName));
            }
        }

        TArray<TSharedPtr<FJsonValue>> OldPinIds, NewPinIds;
        for (const FPinSnapshot& Pin : OldPins) OldPinIds.Add(MakeShared<FJsonValueString>(Pin.PinId));
        for (const FPinSnapshot& Pin : NewPins) NewPinIds.Add(MakeShared<FJsonValueString>(Pin.PinId));

        TSharedRef<FJsonObject> Result = MakeShared<FJsonObject>();
        Result->SetStringField(TEXT("nodeGuid"), NodeGuid);
        Result->SetStringField(TEXT("graphName"), GraphName);
        Result->SetArrayField(TEXT("oldPinIds"), OldPinIds);
        Result->SetArrayField(TEXT("newPinIds"), NewPinIds);
        Result->SetArrayField(TEXT("pinNameMapping"), Mapping);
        Result->SetArrayField(TEXT("orphanedPins"), Orphaned);
        Result->SetBoolField(TEXT("requiresManualAttention"), Orphaned.Num() > 0);
        return Result;
    }
}

bool UnrealMCP::CallSiteRefresh::RefreshCallSitesInBlueprint(
    const FString& CallerObjectPath,
    const TArray<FCallSiteRow>& CallerRows,
    const FOptions& Options,
    const TSharedRef<FJsonObject>& OutResult)
{
    TArray<FNodeOutcome> Outcomes;
    bool bCompiled = false, bCompileSucceeded = false, bCompileSkipped = false;
    bool bRolledBack = false, bDirty = false;
    bool bGraphRestored = false, bDirtyRestored = false, bRestorationVerified = false;
    int32 CompileErrors = 0, CompileWarnings = 0;
    FString AssetError;

    const bool bAssetSucceeded = BlueprintToolUtils::ExecuteOnGameThreadSync(
        [&](FString& OutError) -> bool
        {
            UBlueprint* CallerBlueprint = nullptr;
            if (!BlueprintEditToolUtils::ResolveBlueprint(CallerObjectPath, CallerBlueprint, OutError))
            {
                return false;
            }

            // Resolve every requested row up front in both modes. A row that no longer resolves is a
            // real caller failure (usually a stale index), not something to silently skip.
            TArray<UK2Node_CallFunction*> CallNodes;
            TArray<UEdGraph*> Graphs;
            bool bAllResolved = true;
            for (const FCallSiteRow& Row : CallerRows)
            {
                UEdGraph* Graph = nullptr;
                FString ResolveError;
                UEdGraphNode* Node = FindCallSiteNode(CallerBlueprint, Row.GraphName, Row.NodeGuid, Graph, ResolveError);
                UK2Node_CallFunction* CallNode = Cast<UK2Node_CallFunction>(Node);

                FNodeOutcome Outcome;
                Outcome.NodeGuid = Row.NodeGuid;
                Outcome.GraphName = Row.GraphName;
                Outcome.bFound = CallNode != nullptr;
                if (CallNode == nullptr)
                {
                    Outcome.Error = ResolveError.IsEmpty()
                        ? (Node != nullptr
                            ? TEXT("The indexed node is not a function-call node.")
                            : TEXT("The indexed call site no longer resolves; rebuild the project index."))
                        : ResolveError;
                    bAllResolved = false;
                }
                Outcomes.Add(MoveTemp(Outcome));
                CallNodes.Add(CallNode);
                Graphs.Add(Graph);
            }

            if (Options.bDryRun)
            {
                bCompileSkipped = true;
                if (!bAllResolved)
                {
                    OutError = TEXT("One or more indexed call sites no longer resolve; rebuild the project index before refreshing.");
                }
                return bAllResolved;
            }

            if (!bAllResolved)
            {
                // Refuse to half-apply: an unresolvable row means the indexed plan does not match the
                // live graphs, so nothing is mutated and the caller is told to reindex.
                OutError = TEXT("One or more indexed call sites no longer resolve; nothing was reconstructed. Rebuild the project index and retry.");
                return false;
            }

            UPackage* CallerPackage = CallerBlueprint->GetPackage();
            const bool bPackageWasDirty = CallerPackage != nullptr && CallerPackage->IsDirty();

            FMutationRequestTracker::Get().Update(Options.OperationId, EMutationRequestState::Mutating,
                FString::Printf(TEXT("Reconstructing %d call node(s) in %s."), CallerRows.Num(), *CallerObjectPath));

            // The transaction must be closed before any UndoTransaction() below: UTransBuffer refuses to
            // undo while a transaction is still open, so rolling back from inside this scope would
            // silently never restore anything. Matches ApplyBlueprintGraphPatchTool's scoping.
            {
                const FScopedTransaction Transaction(NSLOCTEXT("UnrealMCP", "RefreshBlueprintCallSites", "UnrealMCP Refresh Blueprint Call Sites"));
                CallerBlueprint->Modify();
                for (int32 Index = 0; Index < CallerRows.Num(); ++Index)
                {
                    Graphs[Index]->Modify();
                    Outcomes[Index].Evidence = ReconstructNode(
                        CallNodes[Index], CallerRows[Index].NodeGuid, CallerRows[Index].GraphName, Outcomes[Index].BeforePins);
                }
                FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(CallerBlueprint);
            }

            bDirty = CallerPackage != nullptr && CallerPackage->IsDirty();

            if (!Options.bCompileCallers)
            {
                bCompileSkipped = true;
                return true;
            }

            FMutationRequestTracker::Get().Update(Options.OperationId, EMutationRequestState::Compiling,
                FString::Printf(TEXT("Compiling %s after call-site reconstruction."), *CallerObjectPath));
            FCompilerResultsLog Log;
            Log.bSilentMode = true;
            FKismetEditorUtilities::CompileBlueprint(
                CallerBlueprint, EBlueprintCompileOptions::SkipSave | EBlueprintCompileOptions::SkipGarbageCollection, &Log);
            bCompiled = true;
            CompileErrors = Log.NumErrors;
            CompileWarnings = Log.NumWarnings;
            bCompileSucceeded = CompileErrors == 0
                && (CallerBlueprint->Status == BS_UpToDate || CallerBlueprint->Status == BS_UpToDateWithWarnings);
            if (bCompileSucceeded)
            {
                // Never save here: saving affected callers is an explicit later step (SaveValidatedBlueprints).
                return true;
            }

            bRolledBack = GEditor != nullptr && GEditor->UndoTransaction();
            if (bRolledBack)
            {
                FMutationRequestTracker::Get().Update(Options.OperationId, EMutationRequestState::RolledBack,
                    FString::Printf(TEXT("Compilation failed after reconstruction; %s rolled back."), *CallerObjectPath));
                FCompilerResultsLog RollbackLog;
                RollbackLog.bSilentMode = true;
                FKismetEditorUtilities::CompileBlueprint(
                    CallerBlueprint, EBlueprintCompileOptions::SkipSave | EBlueprintCompileOptions::SkipGarbageCollection, &RollbackLog);

                // Prove the rollback rather than assuming it: re-resolve each node and compare its pin
                // shape against the snapshot taken before reconstruction.
                bGraphRestored = true;
                for (FNodeOutcome& Outcome : Outcomes)
                {
                    UEdGraph* RestoredGraph = nullptr;
                    FString RestoreError;
                    UEdGraphNode* RestoredNode = FindCallSiteNode(CallerBlueprint, Outcome.GraphName, Outcome.NodeGuid, RestoredGraph, RestoreError);
                    const UK2Node_CallFunction* RestoredCall = Cast<UK2Node_CallFunction>(RestoredNode);
                    const bool bNodeRestored = RestoredCall != nullptr && PinShapesMatch(Outcome.BeforePins, SnapshotPins(RestoredCall));
                    if (Outcome.Evidence.IsValid())
                    {
                        Outcome.Evidence->SetBoolField(TEXT("restored"), bNodeRestored);
                    }
                    bGraphRestored &= bNodeRestored;
                }
                bRestorationVerified = true;

                if (CallerPackage != nullptr)
                {
                    // The package dirty flag is not transacted, so the undo alone never clears it.
                    CallerPackage->SetDirtyFlag(bPackageWasDirty);
                }
            }
            bDirty = CallerPackage != nullptr && CallerPackage->IsDirty();
            bDirtyRestored = bDirty == bPackageWasDirty;

            OutError = FString::Printf(
                TEXT("Blueprint compilation failed with %d error(s); rolledBack=%s, graphRestored=%s, dirtyRestored=%s."),
                CompileErrors,
                bRolledBack ? TEXT("true") : TEXT("false"),
                bGraphRestored ? TEXT("true") : TEXT("false"),
                bDirtyRestored ? TEXT("true") : TEXT("false"));
            return false;
        },
        AssetError);

    TArray<TSharedPtr<FJsonValue>> NodeResults;
    for (const FNodeOutcome& Outcome : Outcomes)
    {
        TSharedRef<FJsonObject> Item = Outcome.Evidence.IsValid() ? Outcome.Evidence.ToSharedRef() : MakeShared<FJsonObject>();
        if (!Outcome.Evidence.IsValid())
        {
            Item->SetStringField(TEXT("nodeGuid"), Outcome.NodeGuid);
            Item->SetStringField(TEXT("graphName"), Outcome.GraphName);
        }
        Item->SetBoolField(TEXT("found"), Outcome.bFound);
        Item->SetStringField(TEXT("error"), Outcome.Error);
        NodeResults.Add(MakeShared<FJsonValueObject>(Item));
    }

    OutResult->SetStringField(TEXT("objectPath"), CallerObjectPath);
    OutResult->SetBoolField(TEXT("succeeded"), bAssetSucceeded);
    OutResult->SetArrayField(TEXT("nodesReconstructed"), NodeResults);
    OutResult->SetBoolField(TEXT("compiled"), bCompiled);
    OutResult->SetBoolField(TEXT("compileSkipped"), bCompileSkipped);
    OutResult->SetBoolField(TEXT("compileSucceeded"), bCompileSucceeded);
    OutResult->SetNumberField(TEXT("compileErrors"), CompileErrors);
    OutResult->SetNumberField(TEXT("compileWarnings"), CompileWarnings);
    OutResult->SetBoolField(TEXT("rolledBack"), bRolledBack);
    OutResult->SetBoolField(TEXT("restorationVerified"), bRestorationVerified);
    OutResult->SetBoolField(TEXT("graphRestored"), bGraphRestored);
    OutResult->SetBoolField(TEXT("dirtyRestored"), bDirtyRestored);
    OutResult->SetBoolField(TEXT("dirty"), bDirty);
    OutResult->SetStringField(TEXT("error"), AssetError);
    OutResult->SetStringField(TEXT("indexRefreshNote"),
        Options.bRefreshIndex ? TEXT("refreshIndex has no effect until this asset is saved; refresh the index after saving.") : FString());

    return bAssetSucceeded;
}
